### PR TITLE
UI fixes

### LINKED ISSUE #112: BUG - Validation is not working on submit
Formik form should touch all fields on submit and therefore validate on fields. This touch is not happening and validation is not working

### PR DESCRIPTION
**Pull request by NiklasMenard**
Burger menu, fixed validation bug, snackbar when creating game, ui fixes

### CODE REVIEW

File: src/components/CreateGameForm.js [hunk 1]
```diff
@@ -71,7 +105,7 @@ const CreateFieldSet = ({ matchData, singleGameView }) => {
       joinMatch({
         variables: {
           input: {
-            matchId: window.location.pathname.slice(13),
+            matchId: +window.location.pathname.slice(13),
```
Comment (jukkah) [inline src/components/CreateGameForm.js]: Match id will not be number so casting hash to number will result NaN

File: src/components/CreateGameForm.js [hunk 2]
```diff
@@ -80,7 +114,7 @@ const CreateFieldSet = ({ matchData, singleGameView }) => {
       joinAnonymously({
         variables: {
           input: {
-            matchId: window.location.pathname.slice(13),
+            matchId: +window.location.pathname.slice(13),
```
Comment (jukkah) [inline src/components/CreateGameForm.js]: Same here

**Review by jukkah — CHANGES_REQUESTED** [review]

**Review by jukkah — APPROVED** [review]
lgtm
